project:
  type: website
  output-dir: docs

website:
  title: "Meeval Augustine"
  site-url: "https://Meeval20.github.io/Portfolio"
  favicon: "images/favicon.ico"
  navbar:
    logo: "images/logo.png"
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/Meeval20
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/meeval-augustine-60518323a
        target: _blank
  page-footer:
    left: "© 2025 Meeval Augustine. Built with [Quarto](https://quarto.org/)."

format:
  html:
    theme:
      - lux
      - styles.scss
    toc: true
    code-fold: true
    code-tools: false
