---
toc: false
---

::: {style="display: flex; flex-direction: column; justify-content: center; align-items: center; min-height: 65vh; text-align: center; max-width: 800px; margin: 0 auto; gap: 1rem;"}

# REFLECTION

Overall, as I built my e-portfolio and further developed my understanding of business analytics principles, I acquired numerous valuable skills both in technical and non-technical aspects that I consider useful for my personal growth and professional development. In the technical front, one of the main tasks I accomplished was to successfully construct a e-portfolio. This enabled me to learn how to properly structure and present my projects in a well organized and professional manner, so that potential employers are able to fully appreciate my capabilities.

As well as the design of the e-portfolio, I also attained some initial technical proficiency on several software programs and platforms. These included, I learned to use Quarto, for producing well-documented and dynamic reports. I also learnt the usage of Git and GitHub for version control and teamwork with others. As well as basic knowledge on how web pages are formatted and styled with HTML and CSS. These learned skills, gave me the base to effectively organize, update, and showcase my work as well as to manage any modifications or edits to the e-portfolio, which was particularly helpful for customization purposes.

I now have a much better idea on how to be an efficient business analyst. This course provided me with practical skills, understanding on the importance of data-driven decisions and analysis in business problem solving, and communication in clear terms when discussing business analytical reports. This was really beneficial for gaining awareness of how to be effective business analyst.

A final outcome from this course, that I found very valuable, was to have acquired some idea of the pathway of being a business analyst. I am now aware of the competencies that must be present to be successful, such as strong problem-solving and analytical thinking, and competence with analytical software. And know I feel I have more idea of what I must achieve, like a proper portfolio, experience and skills improvement, in order to stand out in this industry.

:::
